#!/usr/bin/bash

driver=0000:25:00.0    #this is the one that you need to change , just paste the correct filename from /sys/bus/pci/devices

sudo ifconfig wlan0 down
echo "Wlan adapters are down"


echo "Removing Adapter Driver"
sudo echo "1" > /sys/bus/pci/devices/$driver/remove


echo "Resetting adapter list"


echo "Rescanning devices..."
sudo echo "1" > /sys/bus/pci/rescan


echo "Successfull reset"


sudo systemctl restart NetworkManager
echo "Restarting Network Mananger"
